'use client'

import { useEffect, useMemo, useState } from 'react'

export default function Admin() {
  const [authorized,setAuthorized]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('Attendance'),[members,setMembers]=useState<any[]>([]),[attendance,setAttendance]=useState<any[]>([]),[query,setQuery]=useState(''),[date,setDate]=useState('')
  async function login(){setError('');const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){setError(d.error||'Unable to sign in');return}setAuthorized(true)}
  useEffect(()=>{if(!authorized)return;fetch('/api/admin/data').then(async r=>{if(!r.ok){setAuthorized(false);throw new Error()}return r.json()}).then(d=>{setMembers(d.members||[]);setAttendance(d.attendance||[])}).catch(()=>{})},[authorized])
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
  const selectedDate=date||today
  const todays=useMemo(()=>attendance.filter(a=>a.attendance_date===selectedDate && (!query||String(a.member_name).toLowerCase().includes(query.toLowerCase()))),[attendance,selectedDate,query])
  const present=attendance.filter(a=>a.attendance_date===today).length
  if(!authorized)return <main className="admin"><section className="panel" style={{maxWidth:480,margin:'12vh auto'}}><div className="brand">LIFELINE CHOIR</div><h1>Admin Login</h1><p className="muted">Authorized administrators only.</p><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" autoComplete="username"/><input className="input" style={{marginTop:10}} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" autoComplete="current-password"/>{error&&<p className="muted" role="alert">{error}</p>}<button className="primary" style={{marginTop:12}} onClick={login}>SIGN IN</button></section></main>
  return <main className="admin"><header className="adminbar"><div><div className="brand" style={{textAlign:'left'}}>LIFELINE CHOIR</div><h1 style={{margin:'6px 0'}}>Admin Dashboard</h1><div className="muted">Attendance management</div></div><a className="link" href="/">Member check-in →</a></header><nav className="nav">{['Attendance','Members','PINs','Reports'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><section className="panel">
  {tab==='Attendance'&&<><h2>{selectedDate===today?"Today’s Attendance":"Attendance"}</h2><div className="stats"><div className="stat"><span className="muted">Present today</span><strong>{present}</strong></div><div className="stat"><span className="muted">Absent today</span><strong>{Math.max(members.length-present,0)}</strong></div><div className="stat"><span className="muted">Members</span><strong>{members.length}</strong></div><div className="stat"><span className="muted">Rate</span><strong>{members.length?Math.round(present/members.length*100):0}%</strong></div></div><div style={{display:'flex',gap:10,margin:'18px 0',flexWrap:'wrap'}}><input className="input" style={{flex:1,minWidth:220}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search member..."/><input className="input" style={{width:180}} type="date" value={date} onChange={e=>setDate(e.target.value)}/>{date&&<button onClick={()=>setDate('')}>Today</button>}</div>{todays.length?todays.slice(0,100).map(a=><div className="row" key={a.id}><div><strong>✓ {a.member_name}</strong><div className="muted">{a.checked_in_at?new Date(a.checked_in_at).toLocaleTimeString():''}</div></div><span className="pill">PRESENT</span></div>):<p className="muted">No attendance records found.</p>}</>}
  {tab==='Members'&&<><h2>Members</h2><p className="muted">Live registered choir members.</p>{members.map(m=><div className="row" key={m.id}><div><strong>{m.full_name}</strong><div className="muted">{m.voice_part||'Choir member'}</div></div><span className="pill">{m.active===false?'INACTIVE':'ACTIVE'}</span></div>)}</>}
  {tab==='PINs'&&<><h2>PIN Management</h2><p className="muted">Member PINs are protected and never displayed here.</p>{members.map(m=><div className="row" key={m.id}><strong>{m.full_name}</strong><span className="muted">PIN protected</span></div>)}</>}
  {tab==='Reports'&&<><h2>Attendance Reports</h2><p className="muted">{attendance.length} attendance records available.</p><button onClick={()=>{const csv=['Member,Date,Checked In'].concat(attendance.map(a=>`${JSON.stringify(a.member_name)},${a.attendance_date},${a.checked_in_at}`)).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='lifeline-attendance.csv';a.click();URL.revokeObjectURL(u)}}>Download CSV</button></>}
 </section></main>
}
